# Generated by Django 5.2.4 on 2025-07-25 15:03

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("wealthUser", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="NetWorthItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "value",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=15,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "item_type",
                    models.CharField(
                        choices=[("ASSET", "Asset"), ("LIABILITY", "Liability")],
                        max_length=20,
                    ),
                ),
                (
                    "asset_category",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("SAVINGS", "Savings"),
                            ("INVESTMENTS", "Investments"),
                            ("PROPERTY", "Property"),
                            ("OTHER_ASSETS", "Other Assets"),
                        ],
                        help_text="Only applicable for Assets",
                        max_length=20,
                        null=True,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wealthUser.group",
                    ),
                ),
            ],
            options={
                "ordering": ["item_type", "name"],
                "indexes": [
                    models.Index(
                        fields=["group", "item_type"],
                        name="netWorth_ne_group_i_1ce179_idx",
                    ),
                    models.Index(
                        fields=["group", "asset_category"],
                        name="netWorth_ne_group_i_5b1b9e_idx",
                    ),
                ],
            },
        ),
    ]
