# Generated by Django 5.2.4 on 2025-07-25 23:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wealthUser", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Administrator"),
                    ("editor", "Editor"),
                    ("viewer", "Viewer"),
                ],
                default="viewer",
                help_text="User's role within their group",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="is_admin",
            field=models.BooleanField(
                default=False, help_text="System-wide admin (overrides group role)"
            ),
        ),
    ]
